server:
  port: 80


spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: TENGlm123+
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    servlet:
      path: /